apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/30 * * * *"  # Schedule for running the backup every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: backup-service:1.0  # Reference your Docker image here
            volumeMounts:
              - name: data-volume
                mountPath: /app/data  # Mount path inside the container
          restartPolicy: OnFailure
      volumes:
        - name: data-volume  # Define the volume to mount
          persistentVolumeClaim:
            claimName: data-pvc  # Name of the PersistentVolumeClaim
